# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := build_all_android_extensions
### Rules for final target.
$(obj).target/build_all_android_extensions.stamp: TOOLSET := $(TOOLSET)
$(obj).target/build_all_android_extensions.stamp: $(obj).target/admob/admob.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/build_all_android_extensions.stamp
# Add target alias
.PHONY: build_all_android_extensions
build_all_android_extensions: $(obj).target/build_all_android_extensions.stamp

# Add target alias to "all" target.
.PHONY: all
all: build_all_android_extensions

