# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := admob
### Rules for action "javac_admob":
quiet_cmd_admob_admob_gyp_admob_target_javac_admob = ACTION Compiling admob java sources $@
cmd_admob_admob_gyp_admob_target_javac_admob = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd admob; mkdir -p $(obj)/gen/admob; python ../build/android/gyp/javac.py "--output-dir=$(obj)/gen/admob/classes" "--classpath=/home/barry/code/crosswalk-src-android/src/xwalk/app/tools/android/libs/xwalk_app_runtime_java.jar /home/barry/code/android-sdk-linux/platforms/android-20/android.jar /home/barry/code/android-sdk-linux/extras/google/google_play_services/libproject/google-play-services_lib/libs/google-play-services.jar" "--src-gendirs=" "--javac-includes=" "--stamp=$(obj)/gen/admob/compile.stamp" ./src/org/xwalk/extensions/admob.java

$(obj)/gen/admob/compile.stamp: obj := $(abs_obj)
$(obj)/gen/admob/compile.stamp: builddir := $(abs_builddir)
$(obj)/gen/admob/compile.stamp: TOOLSET := $(TOOLSET)
$(obj)/gen/admob/compile.stamp: build/android/gyp/util/build_utils.py build/android/gyp/javac.py admob/src/org/xwalk/extensions/admob.java /home/barry/code/crosswalk-src-android/src/xwalk/app/tools/android/libs/xwalk_app_runtime_java.jar /home/barry/code/android-sdk-linux/platforms/android-20/android.jar /home/barry/code/android-sdk-linux/extras/google/google_play_services/libproject/google-play-services_lib/libs/google-play-services.jar FORCE_DO_CMD
	$(call do_cmd,admob_admob_gyp_admob_target_javac_admob)

all_deps += $(obj)/gen/admob/compile.stamp
action_admob_admob_gyp_admob_target_javac_admob_outputs := $(obj)/gen/admob/compile.stamp

### Rules for action "jar_admob":
quiet_cmd_admob_admob_gyp_admob_target_jar_admob = ACTION Creating admob jar $@
cmd_admob_admob_gyp_admob_target_jar_admob = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd admob; mkdir -p $(obj)/gen/admob; python ../build/android/gyp/jar.py "--classes-dir=$(obj)/gen/admob/classes" "--jar-path=$(obj)/gen/admob/admob.jar" "--excluded-classes=\"*/R.class\" \"*/R##*.class\""

$(obj)/gen/admob/admob.jar: obj := $(abs_obj)
$(obj)/gen/admob/admob.jar: builddir := $(abs_builddir)
$(obj)/gen/admob/admob.jar: TOOLSET := $(TOOLSET)
$(obj)/gen/admob/admob.jar: build/android/gyp/util/build_utils.py build/android/gyp/util/md5_check.py build/android/gyp/jar.py $(obj)/gen/admob/compile.stamp FORCE_DO_CMD
	$(call do_cmd,admob_admob_gyp_admob_target_jar_admob)

all_deps += $(obj)/gen/admob/admob.jar
action_admob_admob_gyp_admob_target_jar_admob_outputs := $(obj)/gen/admob/admob.jar

### Rules for action "extension_admob":
quiet_cmd_admob_admob_gyp_admob_target_extension_admob = ACTION Copying js and json of admob to jar path $@
cmd_admob_admob_gyp_admob_target_extension_admob = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd admob; mkdir -p $(obj)/gen/admob; cp admob.js admob.json "$(obj)/gen/admob"

$(obj)/gen/admob/admob.js: obj := $(abs_obj)
$(obj)/gen/admob/admob.js: builddir := $(abs_builddir)
$(obj)/gen/admob/admob.js: TOOLSET := $(TOOLSET)
$(obj)/gen/admob/admob.js: admob/admob.js admob/admob.json $(obj)/gen/admob/compile.stamp FORCE_DO_CMD
	$(call do_cmd,admob_admob_gyp_admob_target_extension_admob)
$(obj)/gen/admob/admob.json: $(obj)/gen/admob/admob.js
$(obj)/gen/admob/admob.json: ;

all_deps += $(obj)/gen/admob/admob.js $(obj)/gen/admob/admob.json
action_admob_admob_gyp_admob_target_extension_admob_outputs := $(obj)/gen/admob/admob.js $(obj)/gen/admob/admob.json


### Rules for final target.
# Build our special outputs first.
$(obj).target/admob/admob.stamp: | $(action_admob_admob_gyp_admob_target_javac_admob_outputs) $(action_admob_admob_gyp_admob_target_jar_admob_outputs) $(action_admob_admob_gyp_admob_target_extension_admob_outputs)

# Preserve order dependency of special output on deps.
$(action_admob_admob_gyp_admob_target_javac_admob_outputs) $(action_admob_admob_gyp_admob_target_jar_admob_outputs) $(action_admob_admob_gyp_admob_target_extension_admob_outputs): | $(obj).target/build/android/build_output_dirs.stamp

$(obj).target/admob/admob.stamp: TOOLSET := $(TOOLSET)
$(obj).target/admob/admob.stamp: $(obj).target/build/android/build_output_dirs.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/admob/admob.stamp
# Add target alias
.PHONY: admob
admob: $(obj).target/admob/admob.stamp

# Add target alias to "all" target.
.PHONY: all
all: admob

